// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sigesp.Infra.Data.Context;

namespace Sigesp.Infra.Data.Migrations
{
    [DbContext(typeof(SigespDbContext))]
    [Migration("20211207133632_ChangeDiversos")]
    partial class ChangeDiversos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "da8e4f70-8be9-4d8f-a684-5b97f19d252c",
                            Name = "Master",
                            NormalizedName = "MASTER"
                        },
                        new
                        {
                            Id = "b3a5b61d-7ff4-43cb-bad4-a945b150fc72",
                            ConcurrencyStamp = "194c8eaf-4f2e-4d0e-9b45-ab664a763c1e",
                            Name = "Usuarios_Todos",
                            NormalizedName = "USUARIOS_TODOS"
                        },
                        new
                        {
                            Id = "ef60969b-dc27-44dc-b0a8-3c03a522ec64",
                            ConcurrencyStamp = "434a6e92-e432-430c-9587-36656d74f85c",
                            Name = "Dashboard_Todos",
                            NormalizedName = "DASHBOARD_TODOS"
                        },
                        new
                        {
                            Id = "99f6b971-2602-4afb-a9cb-1cec1e7d16fd",
                            ConcurrencyStamp = "f82753c8-86ab-4ee8-85e7-19b357d03eda",
                            Name = "Detentos_Todos",
                            NormalizedName = "DETENTOS_TODOS"
                        },
                        new
                        {
                            Id = "6d8717fd-2ef7-4b01-9302-a5b6e083e0e7",
                            ConcurrencyStamp = "5450a7ae-ed7e-4b72-83b8-945104beed34",
                            Name = "Empresas_Todos",
                            NormalizedName = "EMPRESAS_TODOS"
                        },
                        new
                        {
                            Id = "47d047d6-e7c6-409e-b53c-a9dc66004354",
                            ConcurrencyStamp = "714f94eb-9d78-4e76-a03a-68ac6b5cdab1",
                            Name = "Empresas-Convenios_Todos",
                            NormalizedName = "EMPRESAS-CONVENIOS_TODOS"
                        },
                        new
                        {
                            Id = "e2c6ef91-aa5a-4f30-857c-bd94db0ab240",
                            ConcurrencyStamp = "a709e158-cc19-4db2-8bdb-750e5b3d727f",
                            Name = "Colaboradores_Todos",
                            NormalizedName = "COLABORADORES_TODOS"
                        },
                        new
                        {
                            Id = "96a403a0-28c8-47f2-91e8-0f9df2da00c6",
                            ConcurrencyStamp = "313479a6-94f2-4612-83da-b0850e0ad00e",
                            Name = "Colaboradores_Relatorios",
                            NormalizedName = "COLABORADORES_RELATORIOS"
                        },
                        new
                        {
                            Id = "d9db904b-aee9-4474-9301-e731e7c79cbe",
                            ConcurrencyStamp = "75966e0f-7709-40f4-9e76-938fbe188dd1",
                            Name = "Lancamentos_Todos",
                            NormalizedName = "LANCAMENTOS_TODOS"
                        },
                        new
                        {
                            Id = "e86df548-3cd5-4a3f-b82e-78842186f8d2",
                            ConcurrencyStamp = "8e9bdf9b-04a5-452b-9269-208c99a17f2a",
                            Name = "Contas-Correntes_Todos",
                            NormalizedName = "CONTAS-CORRENTES_TODOS"
                        },
                        new
                        {
                            Id = "dc50c49f-3cef-4dbe-83bb-5f1916ac8854",
                            ConcurrencyStamp = "c98d36df-14df-4cda-ae90-61b30dc86a70",
                            Name = "Contas-Correntes_Relatorios",
                            NormalizedName = "CONTAS-CORRENTES_RELATORIOS"
                        },
                        new
                        {
                            Id = "92c72070-3275-49e6-bd4a-f6c8e565b5bc",
                            ConcurrencyStamp = "610041f7-1332-4769-8d11-7c92b7e90cb1",
                            Name = "Edis_Todos",
                            NormalizedName = "EDIS_TODOS"
                        },
                        new
                        {
                            Id = "e060a6d2-6472-4294-9f68-22bd114867f9",
                            ConcurrencyStamp = "77ea2caa-69a2-4ae4-bf76-cf87d8cef7f6",
                            Name = "Andamento-Penal_Todos",
                            NormalizedName = "ANDAMENTO-PENAL_TODOS"
                        },
                        new
                        {
                            Id = "e6b7ff49-350c-4b89-a533-9eb923d8ba1b",
                            ConcurrencyStamp = "0421080e-e52e-4337-a0e0-3630f83bb58d",
                            Name = "Template",
                            NormalizedName = "TEMPLATE"
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("UserId")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca431822-360a-4ee6-b978-66564d429fc7",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFGbgHKOKiDDs5fvXN8kHviorntHToMKurnVJNmsFQNInxhQOyZTwJ2w0SpbyCdZbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c9514850-61dd-4cc1-b909-88b79b035643",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "1e526008-75f7-4a01-9942-d178f2b38888",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e627e3a3-d53a-4fc9-a87c-32e9ce8e1218",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "SISTEMA@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIW3u0VBTe5BgtXxXDBTs9pxnSdIslsYrAK8y9P4a3S6pT1cmvrWZMX6owmy7TmeAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e90e63a1-e27d-4394-aa4f-3e2b0bbb9f90",
                            TwoFactorEnabled = false,
                            UserName = "sistema@gmail.com"
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "e6b7ff49-350c-4b89-a533-9eb923d8ba1b"
                        },
                        new
                        {
                            UserId = "1e526008-75f7-4a01-9942-d178f2b38888",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BancoAgencia")
                        .HasColumnType("character varying(6)")
                        .HasMaxLength(6);

                    b.Property<string>("BancoConta")
                        .HasColumnType("character varying(6)")
                        .HasMaxLength(6);

                    b.Property<int>("BancoNumero")
                        .HasColumnType("integer")
                        .HasMaxLength(4);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataUltimaSituacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DescontoOutro")
                        .HasColumnType("decimal(4,2)");

                    b.Property<Guid>("DetentoId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiaPagamento")
                        .HasColumnType("integer")
                        .HasMaxLength(2);

                    b.Property<Guid>("EmpresaConvenioId")
                        .HasColumnType("uuid");

                    b.Property<string>("FamiliarAutorizadoRetirada")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemunerado")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrabalhoInterno")
                        .HasColumnType("boolean");

                    b.Property<string>("JornadaFim")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("JornadaInicio")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("LocalTrabalho")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Observacao")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<decimal>("Remuneracao")
                        .HasColumnType("decimal(7,3)");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.Property<int>("TipoConta")
                        .HasColumnType("integer");

                    b.Property<int>("TipoPagamento")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetentoId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("EmpresaConvenioId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("Colaboradores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8cf3741-5bad-49ef-9e94-0e2dbb48ab3a"),
                            BancoAgencia = "654321",
                            BancoConta = "123456",
                            BancoNumero = 341,
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 695, DateTimeKind.Local).AddTicks(9336),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            DataInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataUltimaSituacao = new DateTime(2021, 12, 7, 10, 36, 31, 695, DateTimeKind.Local).AddTicks(3618),
                            Desconto = 25m,
                            DescontoOutro = 33m,
                            DetentoId = new Guid("533ef31e-407a-4da2-a416-53a50ec0da0e"),
                            DiaPagamento = 10,
                            EmpresaConvenioId = new Guid("af1f8d4d-6b2d-413d-8407-9ff99537dad5"),
                            FamiliarAutorizadoRetirada = "Teste",
                            IsDeleted = false,
                            IsRemunerado = true,
                            IsTrabalhoInterno = true,
                            JornadaFim = "17:00",
                            JornadaInicio = "08:00",
                            LocalTrabalho = "GALERIA",
                            Observacao = "Nenhuma observação",
                            Remuneracao = 1000.20m,
                            Situacao = 1,
                            TipoConta = 2,
                            TipoPagamento = 1,
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 695, DateTimeKind.Local).AddTicks(9350),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888")
                        },
                        new
                        {
                            Id = new Guid("08adda92-d549-4065-a9c1-14b1adc26ea8"),
                            BancoAgencia = "897654",
                            BancoConta = "456789",
                            BancoNumero = 1,
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 695, DateTimeKind.Local).AddTicks(9570),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            DataInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataUltimaSituacao = new DateTime(2021, 12, 7, 10, 36, 31, 695, DateTimeKind.Local).AddTicks(9390),
                            Desconto = 25m,
                            DescontoOutro = 33m,
                            DetentoId = new Guid("12fab6de-0f9a-4667-abdf-fe216bb0441f"),
                            DiaPagamento = 5,
                            EmpresaConvenioId = new Guid("87f95ebb-8ee3-4585-a0a5-dc230d036a18"),
                            FamiliarAutorizadoRetirada = "Teste 1",
                            IsDeleted = false,
                            IsRemunerado = true,
                            IsTrabalhoInterno = false,
                            JornadaFim = "14:00",
                            JornadaInicio = "07:30",
                            LocalTrabalho = "Fábrica do conveniado",
                            Observacao = "Nenhuma observação 2",
                            Remuneracao = 1000.20m,
                            Situacao = 2,
                            TipoConta = 3,
                            TipoPagamento = 2,
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 695, DateTimeKind.Local).AddTicks(9575),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888")
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ContaCorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUltimoStatus")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasMaxLength(6);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("Numero");

                    b.ToTable("ContasCorrentes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2358763-f076-4178-8f40-c24eeadf3e96"),
                            ColaboradorId = new Guid("a8cf3741-5bad-49ef-9e94-0e2dbb48ab3a"),
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 700, DateTimeKind.Local).AddTicks(1021),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            DataUltimoStatus = new DateTime(2021, 12, 7, 10, 36, 31, 700, DateTimeKind.Local).AddTicks(261),
                            IsDeleted = false,
                            Numero = 234567,
                            Status = 1,
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 700, DateTimeKind.Local).AddTicks(1037),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888")
                        },
                        new
                        {
                            Id = new Guid("7c656707-a8e5-41ac-be05-4b03ea5c1692"),
                            ColaboradorId = new Guid("08adda92-d549-4065-a9c1-14b1adc26ea8"),
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 700, DateTimeKind.Local).AddTicks(1521),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            DataUltimoStatus = new DateTime(2021, 12, 7, 10, 36, 31, 700, DateTimeKind.Local).AddTicks(1500),
                            IsDeleted = false,
                            Numero = 123456,
                            Status = 1,
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 700, DateTimeKind.Local).AddTicks(1526),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888")
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ContaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Funcao")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("PerfilFoto")
                        .HasColumnType("bytea");

                    b.Property<int>("Setor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ContaUsuarios");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Detento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cela")
                        .HasColumnType("integer")
                        .HasMaxLength(2);

                    b.Property<string>("Cpf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(11)")
                        .HasMaxLength(11)
                        .HasDefaultValue(null);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Galeria")
                        .HasColumnType("character varying(2)")
                        .HasMaxLength(2);

                    b.Property<int>("Ipen")
                        .HasColumnType("integer")
                        .HasMaxLength(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProvisorio")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSaidaTemporaria")
                        .HasColumnType("boolean");

                    b.Property<string>("MatriculaFamiliar")
                        .IsRequired()
                        .HasColumnType("character varying(6)")
                        .HasMaxLength(6);

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NomeFamiliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue(null);

                    b.Property<string>("Pec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("RetornoSaidaTemporaria")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Rg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("SaidaTemporaria")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Ipen")
                        .IsUnique();

                    b.HasIndex("MatriculaFamiliar")
                        .IsUnique();

                    b.ToTable("Detentos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12fab6de-0f9a-4667-abdf-fe216bb0441f"),
                            Cela = 2,
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 679, DateTimeKind.Local).AddTicks(6902),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            Galeria = "A",
                            Ipen = 123456,
                            IsDeleted = false,
                            IsProvisorio = false,
                            IsSaidaTemporaria = true,
                            MatriculaFamiliar = "000001",
                            Nascimento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Detento 1",
                            NomeFamiliar = "Maria de Lourdes",
                            RetornoSaidaTemporaria = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaidaTemporaria = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Situacao = 7,
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 680, DateTimeKind.Local).AddTicks(7565),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888")
                        },
                        new
                        {
                            Id = new Guid("533ef31e-407a-4da2-a416-53a50ec0da0e"),
                            Cela = 10,
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 680, DateTimeKind.Local).AddTicks(8501),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            Galeria = "D",
                            Ipen = 234567,
                            IsDeleted = false,
                            IsProvisorio = true,
                            IsSaidaTemporaria = false,
                            MatriculaFamiliar = "000002",
                            Nascimento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Detento 2",
                            NomeFamiliar = "Carlos Amarildo de Souza",
                            RetornoSaidaTemporaria = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaidaTemporaria = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Situacao = 8,
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 680, DateTimeKind.Local).AddTicks(8525),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888")
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Cep")
                        .HasColumnType("integer")
                        .HasMaxLength(8);

                    b.Property<string>("Cidade")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Cnpj")
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Estado")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Logradouro")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Numero")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Responsavel")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("TelefoneCelular")
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.Property<string>("TelefoneFixo")
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00e08a3e-da29-4493-8786-65c67a98970f"),
                            Bairro = "Comerciário",
                            Cep = 12345678,
                            Cidade = "Criciúma",
                            Cnpj = "12345678912345",
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 686, DateTimeKind.Local).AddTicks(5106),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            Estado = "Santa Catarina",
                            IsDeleted = false,
                            Logradouro = "Rua teste",
                            NomeFantasia = "RBX",
                            Numero = "10",
                            RazaoSocial = "RBX Alimentos",
                            Responsavel = "João da silva",
                            TelefoneCelular = "12345678912345",
                            TelefoneFixo = "12345678912345",
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 686, DateTimeKind.Local).AddTicks(5143),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            WhatsApp = "12345678912345"
                        },
                        new
                        {
                            Id = new Guid("6ba1a56a-e931-4ccd-baf0-bdf907aa8b61"),
                            Bairro = "Urussanguinha",
                            Cep = 12345678,
                            Cidade = "Urussanga",
                            Cnpj = "12345678912345",
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 686, DateTimeKind.Local).AddTicks(5305),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            Estado = "Santa Catarina",
                            IsDeleted = false,
                            Logradouro = "Rua teste",
                            NomeFantasia = "ESAF",
                            Numero = "20",
                            RazaoSocial = "ESAF Ferragens",
                            Responsavel = "Geraldo Fornazza",
                            TelefoneCelular = "12345678912345",
                            TelefoneFixo = "12345678912345",
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 686, DateTimeKind.Local).AddTicks(5311),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            WhatsApp = "12345678912345"
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.EmpresaConvenio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEncerramento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRenovacaoAutomatica")
                        .HasColumnType("boolean");

                    b.Property<string>("MotivoEncerramento")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Responsavel")
                        .HasColumnType("text");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.Property<string>("TermosGerais")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("EmpresasConvenios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87f95ebb-8ee3-4585-a0a5-dc230d036a18"),
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 690, DateTimeKind.Local).AddTicks(4202),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            DataEncerramento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2021, 12, 7, 10, 36, 31, 690, DateTimeKind.Local).AddTicks(2397),
                            DataInicio = new DateTime(2021, 12, 7, 10, 36, 31, 690, DateTimeKind.Local).AddTicks(1990),
                            EmpresaId = new Guid("00e08a3e-da29-4493-8786-65c67a98970f"),
                            IsDeleted = false,
                            IsRenovacaoAutomatica = true,
                            Nome = "Convenio RBX",
                            Responsavel = "Amilton luiz",
                            Situacao = 1,
                            TermosGerais = "Conforme acordado em contrato",
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 690, DateTimeKind.Local).AddTicks(4217),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888")
                        },
                        new
                        {
                            Id = new Guid("af1f8d4d-6b2d-413d-8407-9ff99537dad5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            DataEncerramento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2021, 12, 7, 10, 36, 31, 690, DateTimeKind.Local).AddTicks(4262),
                            DataInicio = new DateTime(2021, 12, 7, 10, 36, 31, 690, DateTimeKind.Local).AddTicks(4252),
                            EmpresaId = new Guid("6ba1a56a-e931-4ccd-baf0-bdf907aa8b61"),
                            IsDeleted = false,
                            IsRenovacaoAutomatica = true,
                            Nome = "Convenio ESAF",
                            Responsavel = "José luiz datena",
                            Situacao = 2,
                            TermosGerais = "Termos acertados no contrato",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888")
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaCorrenteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataLiquidacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataUltimoStatus")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int>("PeriodoDataFim")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodoDataInicio")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodoReferencia")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaCorrenteId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("Lancamentos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0af820ce-7131-45de-a98d-947f972c2a84"),
                            ContaCorrenteId = new Guid("f2358763-f076-4178-8f40-c24eeadf3e96"),
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 703, DateTimeKind.Local).AddTicks(6400),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            DataLiquidacao = new DateTime(2021, 12, 7, 10, 36, 31, 703, DateTimeKind.Local).AddTicks(1986),
                            DataUltimoStatus = new DateTime(2021, 12, 7, 10, 36, 31, 703, DateTimeKind.Local).AddTicks(4886),
                            Desconto = 100.25m,
                            Descricao = "Pagamento mensal 1",
                            IsDeleted = false,
                            Observacao = "Informações teste registro 1",
                            PeriodoDataFim = 31,
                            PeriodoDataInicio = 1,
                            PeriodoReferencia = 1,
                            Status = 1,
                            Tipo = 1,
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 703, DateTimeKind.Local).AddTicks(6419),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            ValorBruto = 1000.20m,
                            ValorLiquido = 900.10m
                        },
                        new
                        {
                            Id = new Guid("f9ccef5e-d217-485f-91de-97cd93efca3a"),
                            ContaCorrenteId = new Guid("f2358763-f076-4178-8f40-c24eeadf3e96"),
                            CreatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 703, DateTimeKind.Local).AddTicks(6951),
                            CreatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            DataLiquidacao = new DateTime(2021, 12, 7, 10, 36, 31, 703, DateTimeKind.Local).AddTicks(6815),
                            DataUltimoStatus = new DateTime(2021, 12, 7, 10, 36, 31, 703, DateTimeKind.Local).AddTicks(6872),
                            Desconto = 255.70m,
                            Descricao = "Pagamento mensal 2",
                            IsDeleted = false,
                            Observacao = "Informações teste registro 2",
                            PeriodoDataFim = 31,
                            PeriodoDataInicio = 1,
                            PeriodoReferencia = 4,
                            Status = 2,
                            Tipo = 1,
                            UpdatedAt = new DateTime(2021, 12, 7, 10, 36, 31, 703, DateTimeKind.Local).AddTicks(6956),
                            UpdatedBy = new Guid("1e526008-75f7-4a01-9942-d178f2b38888"),
                            ValorBruto = 1000.20m,
                            ValorLiquido = 600.44m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationUserClaim", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", null)
                        .WithMany("ApplicationUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationRole", "ApplicationRole")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Colaborador", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Detento", "Detento")
                        .WithOne("Colaborador")
                        .HasForeignKey("Sigesp.Domain.Models.Colaborador", "DetentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.EmpresaConvenio", "EmpresaConvenio")
                        .WithMany("Colaboradores")
                        .HasForeignKey("EmpresaConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ContaCorrente", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Colaborador", "Colaborador")
                        .WithOne("ContaCorrente")
                        .HasForeignKey("Sigesp.Domain.Models.ContaCorrente", "ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ContaUsuario", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("ContaUsuario")
                        .HasForeignKey("Sigesp.Domain.Models.ContaUsuario", "UserId");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.EmpresaConvenio", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Empresa", "Empresa")
                        .WithMany("EmpresaConvenios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Lancamento", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ContaCorrente", "ContaCorrente")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
