// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sigesp.Infra.Data.Context;

namespace Sigesp.Infra.Data.Migrations
{
    [DbContext(typeof(SigespDbContext))]
    [Migration("20220708171030_CreateMigrationsChangesInAlunoEjaAndAlunoEjaDisciplinas")]
    partial class CreateMigrationsChangesInAlunoEjaAndAlunoEjaDisciplinas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:Enum:instrumento_prisao_tipo_enum", "nenhum,nota_culpa,mandado_prisao,transferencia,recaptura,medida_disciplinar")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<int[]>("AtividadesEducacionais")
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("CejaDataMatricula")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CejaId")
                        .HasColumnType("text");

                    b.Property<string>("CejaMatricula")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataPedidoEnturmacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DetentoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Escolaridade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnturmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TurmaNumero")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<string>("TurmaSala")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetentoId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoEja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Curso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("DataIngresso")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataOcorrenciaDesistencia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int[]>("Disciplinas")
                        .HasColumnType("integer[]");

                    b.Property<int>("EjaOcorrenciaDesistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Fase")
                        .HasColumnType("integer");

                    b.Property<int>("FaseStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("TurnoPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("AlunosEja");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoEjaDisciplina", b =>
                {
                    b.Property<Guid>("AlunoEjaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Conceito")
                        .HasColumnType("integer");

                    b.Property<int>("Nome")
                        .HasColumnType("integer");

                    b.HasIndex("AlunoEjaId");

                    b.ToTable("AlunoEjaDisciplinas");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoEncceja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Curso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DataProva")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HasCertificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("InscricaoNumero")
                        .HasColumnType("text");

                    b.Property<bool>("IsAprovado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Media")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaAreaI")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaAreaII")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaAreaIII")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaAreaIV")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaRedacao")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("AlunosEncceja");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoEnem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataProva")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HasMediaMinima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("InscricaoNumero")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LinguaEstrangeira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("Media")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaCH")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaCN")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaLC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaMT")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaRedacao")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("AlunosEnem");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoLeitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataIngresso")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataOcorrenciaDesistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LivroGeneroId")
                        .HasColumnType("uuid");

                    b.Property<int>("OcorrenciaDesistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.HasIndex("LivroGeneroId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("ProfessorId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("AlunosLeitores");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoLeitura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoLeitorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoLeituraCronogramaId")
                        .HasColumnType("uuid");

                    b.Property<int>("AvaliacaoConceito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("AvaliacaoConceitoJustificativa")
                        .HasColumnType("text");

                    b.Property<int>("AvaliacaoCriterio1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("AvaliacaoCriterio2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("AvaliacaoCriterio3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("AvaliacaoCriterio4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("AvaliacaoCriterio5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("AvaliacaoCriterio6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("AvaliacaoCriterio7")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("AvaliacaoObservacao")
                        .HasColumnType("text");

                    b.Property<long>("ChaveLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasMaxLength(10)
                        .HasDefaultValue(0L);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LeituraTipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("LivroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoLeitorId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("AlunoLeituraCronogramaId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("LivroId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("AlunosLeituras");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoLeituraCronograma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnoReferencia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DiasPeriodo")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime>("PeriodoFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PeriodoInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PeriodoReferencia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AlunosLeiturasCronogramas");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoRedacaoDPU", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CertificadoImagem")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataLimiteEntregaRedacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Etapa")
                        .HasColumnType("integer");

                    b.Property<string>("InscricaoNumero")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivadoLiberdade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Media")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaClareza")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaConteudo")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaCriatividade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaPertinencia")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<string>("RedacaoImagem")
                        .HasColumnType("text");

                    b.Property<int>("ResultadoColocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("ProfessorId");

                    b.ToTable("AlunosRedacaoDPU");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AndamentoPenal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEventoPrincipal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DetentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnderecoCompleto")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Historico")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Pec")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetentoId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("AndamentoPenal");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "da8e4f70-8be9-4d8f-a684-5b97f19d252c",
                            Name = "Master",
                            NormalizedName = "MASTER"
                        },
                        new
                        {
                            Id = "b3a5b61d-7ff4-43cb-bad4-a945b150fc72",
                            ConcurrencyStamp = "194c8eaf-4f2e-4d0e-9b45-ab664a763c1e",
                            Name = "Usuarios_Todos",
                            NormalizedName = "USUARIOS_TODOS"
                        },
                        new
                        {
                            Id = "ef60969b-dc27-44dc-b0a8-3c03a522ec64",
                            ConcurrencyStamp = "434a6e92-e432-430c-9587-36656d74f85c",
                            Name = "Dashboard_Todos",
                            NormalizedName = "DASHBOARD_TODOS"
                        },
                        new
                        {
                            Id = "99f6b971-2602-4afb-a9cb-1cec1e7d16fd",
                            ConcurrencyStamp = "f82753c8-86ab-4ee8-85e7-19b357d03eda",
                            Name = "Detentos_Todos",
                            NormalizedName = "DETENTOS_TODOS"
                        },
                        new
                        {
                            Id = "6d8717fd-2ef7-4b01-9302-a5b6e083e0e7",
                            ConcurrencyStamp = "5450a7ae-ed7e-4b72-83b8-945104beed34",
                            Name = "Empresas_Todos",
                            NormalizedName = "EMPRESAS_TODOS"
                        },
                        new
                        {
                            Id = "47d047d6-e7c6-409e-b53c-a9dc66004354",
                            ConcurrencyStamp = "714f94eb-9d78-4e76-a03a-68ac6b5cdab1",
                            Name = "Empresas-Convenios_Todos",
                            NormalizedName = "EMPRESAS-CONVENIOS_TODOS"
                        },
                        new
                        {
                            Id = "e2c6ef91-aa5a-4f30-857c-bd94db0ab240",
                            ConcurrencyStamp = "a709e158-cc19-4db2-8bdb-750e5b3d727f",
                            Name = "Colaboradores_Todos",
                            NormalizedName = "COLABORADORES_TODOS"
                        },
                        new
                        {
                            Id = "96a403a0-28c8-47f2-91e8-0f9df2da00c6",
                            ConcurrencyStamp = "313479a6-94f2-4612-83da-b0850e0ad00e",
                            Name = "Colaboradores_Relatorios",
                            NormalizedName = "COLABORADORES_RELATORIOS"
                        },
                        new
                        {
                            Id = "d9db904b-aee9-4474-9301-e731e7c79cbe",
                            ConcurrencyStamp = "75966e0f-7709-40f4-9e76-938fbe188dd1",
                            Name = "Lancamentos_Todos",
                            NormalizedName = "LANCAMENTOS_TODOS"
                        },
                        new
                        {
                            Id = "e86df548-3cd5-4a3f-b82e-78842186f8d2",
                            ConcurrencyStamp = "8e9bdf9b-04a5-452b-9269-208c99a17f2a",
                            Name = "Contas-Correntes_Todos",
                            NormalizedName = "CONTAS-CORRENTES_TODOS"
                        },
                        new
                        {
                            Id = "dc50c49f-3cef-4dbe-83bb-5f1916ac8854",
                            ConcurrencyStamp = "c98d36df-14df-4cda-ae90-61b30dc86a70",
                            Name = "Contas-Correntes_Relatorios",
                            NormalizedName = "CONTAS-CORRENTES_RELATORIOS"
                        },
                        new
                        {
                            Id = "92c72070-3275-49e6-bd4a-f6c8e565b5bc",
                            ConcurrencyStamp = "610041f7-1332-4769-8d11-7c92b7e90cb1",
                            Name = "Edis_Todos",
                            NormalizedName = "EDIS_TODOS"
                        },
                        new
                        {
                            Id = "e060a6d2-6472-4294-9f68-22bd114867f9",
                            ConcurrencyStamp = "77ea2caa-69a2-4ae4-bf76-cf87d8cef7f6",
                            Name = "Andamento-Penal_Todos",
                            NormalizedName = "ANDAMENTO-PENAL_TODOS"
                        },
                        new
                        {
                            Id = "e6b7ff49-350c-4b89-a533-9eb923d8ba1b",
                            ConcurrencyStamp = "0421080e-e52e-4337-a0e0-3630f83bb58d",
                            Name = "Template",
                            NormalizedName = "TEMPLATE"
                        },
                        new
                        {
                            Id = "ba56983e-f96f-4009-afe1-96586b830a93",
                            ConcurrencyStamp = "729acc13-9d1a-436b-bcea-2d0231b09c38",
                            Name = "Usuarios_Perfil",
                            NormalizedName = "USUARIOS_PERFIL"
                        },
                        new
                        {
                            Id = "429b409b-b8b3-4410-8e0a-ad36b4f1a554",
                            ConcurrencyStamp = "79729e9c-ca38-4de7-bf1b-e30e778c4def",
                            Name = "Lista-Amarela_Todos",
                            NormalizedName = "LISTA-AMARELA_TODOS"
                        },
                        new
                        {
                            Id = "2238a399-29e0-4b50-971a-e42bf0dfb219",
                            ConcurrencyStamp = "6b2bb02e-96e4-448a-855f-f480cd110f9f",
                            Name = "Sequencias-Oficios_Todos",
                            NormalizedName = "SEQUENCIAS-OFICIOS_TODOS"
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("UserId")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca431822-360a-4ee6-b978-66564d429fc7",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFGbgHKOKiDDs5fvXN8kHviorntHToMKurnVJNmsFQNInxhQOyZTwJ2w0SpbyCdZbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c9514850-61dd-4cc1-b909-88b79b035643",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "1e526008-75f7-4a01-9942-d178f2b38888",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e627e3a3-d53a-4fc9-a87c-32e9ce8e1218",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "SISTEMA@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIW3u0VBTe5BgtXxXDBTs9pxnSdIslsYrAK8y9P4a3S6pT1cmvrWZMX6owmy7TmeAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e90e63a1-e27d-4394-aa4f-3e2b0bbb9f90",
                            TwoFactorEnabled = false,
                            UserName = "sistema@gmail.com"
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "e6b7ff49-350c-4b89-a533-9eb923d8ba1b"
                        },
                        new
                        {
                            UserId = "1e526008-75f7-4a01-9942-d178f2b38888",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        });
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BancoAgencia")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<string>("BancoConta")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<int?>("BancoNumero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasMaxLength(25)
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataUltimaSituacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DemissaoData")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DemissaoObservacao")
                        .HasColumnType("text");

                    b.Property<int>("DemissaoOcorrencia")
                        .HasColumnType("integer");

                    b.Property<decimal>("Desconto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DescontoOutro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("DetentoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DiaPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasMaxLength(2)
                        .HasDefaultValue(0);

                    b.Property<Guid>("EmpresaConvenioId")
                        .HasColumnType("uuid");

                    b.Property<string>("FamiliarAutorizadoRetirada")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Folga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue(null);

                    b.Property<int>("Funcao")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemunerado")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrabalhoInterno")
                        .HasColumnType("boolean");

                    b.Property<string>("JornadaFim")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("JornadaInicio")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("LocalTrabalho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue(null);

                    b.Property<string>("Observacao")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<decimal>("Remuneracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(7,3)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.Property<int>("TipoConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TipoPagamento")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetentoId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("EmpresaConvenioId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ColaboradorPonto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EdiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresaConvenioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PeriodoDataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PeriodoDataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PeriodoReferencia")
                        .HasColumnType("character varying(9)")
                        .HasMaxLength(9);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("EdiId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("EmpresaConvenioId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("ColaboradoresPontos");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ColaboradorPontoApontamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColaboradorPontoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorPontoId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("ColaboradoresPontosApontamentos");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ContaCorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ColaboradorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUltimoStatus")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasMaxLength(6);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("EmpresaId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("Numero");

                    b.ToTable("ContasCorrentes");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ContaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnName("Funcao")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PerfilFoto")
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnName("Setor")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ContaUsuarios");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ContabilEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Especificacao")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ContabilEventos");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Detento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<int>("Cela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasMaxLength(2)
                        .HasDefaultValue(0);

                    b.Property<int>("Cep")
                        .HasColumnType("integer");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(11)")
                        .HasMaxLength(11)
                        .HasDefaultValue(null);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Galeria")
                        .HasColumnType("character varying(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Idade")
                        .HasColumnType("text");

                    b.Property<int>("Ipen")
                        .HasColumnType("integer")
                        .HasMaxLength(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProvisorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSaidaTemporaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Logradouro")
                        .HasColumnType("text");

                    b.Property<string>("MatriculaFamiliar")
                        .IsRequired()
                        .HasColumnType("character varying(6)")
                        .HasMaxLength(6);

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NomeFamiliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue(null);

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Pec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue(null);

                    b.Property<int>("Regime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Rg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue(null);

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransferenciaDataRetornoPrevisto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TransferenciaDataRetornoRealizado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TransferenciaDataSaida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TransferenciaLocal")
                        .HasColumnType("text");

                    b.Property<int>("TransferenciaTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Ipen")
                        .IsUnique();

                    b.HasIndex("MatriculaFamiliar")
                        .IsUnique();

                    b.ToTable("Detentos");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.DetentoSaidaTemporaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetentoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RetornoPrevisto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SaidaPrevista")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetentoId");

                    b.ToTable("DetentoSaidasTemporaria");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Disciplina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CargaHoraria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Curso")
                        .HasColumnType("integer");

                    b.Property<int>("Fase")
                        .HasColumnType("integer");

                    b.Property<int>("HoraAula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Edi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ArquivoExtensao")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("ArquivoNome")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FullPath")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Edis");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.EdiLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EdiId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EntityProperty")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EntityPropertyNewValue")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EntityPropertyOldValue")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EdiId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("EdisLogs");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Cep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasMaxLength(8)
                        .HasDefaultValue(0);

                    b.Property<string>("Cidade")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Cnpj")
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Estado")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Logradouro")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Numero")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Responsavel")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("TelefoneCelular")
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.Property<string>("TelefoneFixo")
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.EmpresaConvenio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEncerramento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRenovacaoAutomatica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MotivoEncerramento")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Responsavel")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.Property<string>("TermosGerais")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("EmpresasConvenios");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaCorrenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContabilEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataLiquidacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataUltimoStatus")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacao")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int>("PeriodoDataFim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PeriodoDataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PeriodoReferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaCorrenteId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("ContabilEventoId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ListaAmarela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AcaoPenal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue(null);

                    b.Property<bool>("AguardandoTransferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Artigos")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Comarca")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int>("CondenacaoTipo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataPrevisaoBeneficio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("DataPrisao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("DataProgressao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("DataSaidaPrevista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<Guid>("DetentoId")
                        .HasColumnType("uuid");

                    b.Property<long?>("DiasMedidaDisciplinar")
                        .HasColumnType("bigint");

                    b.Property<int[]>("InstrumentosPrisao")
                        .HasColumnType("integer[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PenaAno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(4)")
                        .HasMaxLength(4)
                        .HasDefaultValue(null);

                    b.Property<string>("PenaDia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(12)")
                        .HasMaxLength(12)
                        .HasDefaultValue(null);

                    b.Property<string>("PenaMes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(6)")
                        .HasMaxLength(6)
                        .HasDefaultValue(null);

                    b.Property<string>("PrevisaoBeneficioObservacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue(null);

                    b.Property<DateTime>("RevisaoIpenData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetentoId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("ListaAmarela");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisponivel")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LivroAutorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LivroGeneroId")
                        .HasColumnType("uuid");

                    b.Property<long>("Localizacao")
                        .HasColumnType("bigint");

                    b.Property<string>("Propriedade")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LivroAutorId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.HasIndex("LivroGeneroId")
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.LivroAutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LivrosAutores");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.LivroGenero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LivrosGeneros");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Galeria")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\"='0'");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.SequenciaOficio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Sequencia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UsuarioNomeUltimaSequencia")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SequenciasOficios");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Aluno", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Detento", "Detento")
                        .WithOne("Aluno")
                        .HasForeignKey("Sigesp.Domain.Models.Aluno", "DetentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoEja", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Aluno", "Aluno")
                        .WithMany("AlunosEja")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoEjaDisciplina", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.AlunoEja", "AlunoEja")
                        .WithMany()
                        .HasForeignKey("AlunoEjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoEncceja", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Aluno", "Aluno")
                        .WithMany("AlunosEncceja")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoEnem", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Aluno", "Aluno")
                        .WithMany("AlunosEnem")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoLeitor", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Aluno", "Aluno")
                        .WithMany("AlunosLeitores")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.LivroGenero", "LivroGenero")
                        .WithMany()
                        .HasForeignKey("LivroGeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.Professor", "Professor")
                        .WithMany("AlunosLeitores")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoLeitura", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.AlunoLeitor", "AlunoLeitor")
                        .WithMany("AlunoLeituras")
                        .HasForeignKey("AlunoLeitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.AlunoLeituraCronograma", "AlunoLeituraCronograma")
                        .WithMany("AlunoLeituras")
                        .HasForeignKey("AlunoLeituraCronogramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.Livro", "Livro")
                        .WithMany("AlunoLeituras")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AlunoRedacaoDPU", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Aluno", "Aluno")
                        .WithMany("AlunosRedacaoDPU")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.Professor", "Professor")
                        .WithMany("AlunosRedacaoDPU")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.AndamentoPenal", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Detento", "Detento")
                        .WithOne("AndamentoPenal")
                        .HasForeignKey("Sigesp.Domain.Models.AndamentoPenal", "DetentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationUserClaim", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", null)
                        .WithMany("ApplicationUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationRole", "ApplicationRole")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Colaborador", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Detento", "Detento")
                        .WithMany("Colaboradores")
                        .HasForeignKey("DetentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.EmpresaConvenio", "EmpresaConvenio")
                        .WithMany("Colaboradores")
                        .HasForeignKey("EmpresaConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ColaboradorPonto", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Colaborador", "Colaborador")
                        .WithMany("Pontos")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.Edi", "Edi")
                        .WithMany("ColaboradoresPonto")
                        .HasForeignKey("EdiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.EmpresaConvenio", "EmpresaConvenio")
                        .WithMany("ColaboradoresPonto")
                        .HasForeignKey("EmpresaConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ColaboradorPontoApontamento", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ColaboradorPonto", "ColaboradorPonto")
                        .WithMany("ColaboradorPontoApontamentos")
                        .HasForeignKey("ColaboradorPontoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ContaCorrente", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Colaborador", "Colaborador")
                        .WithOne("ContaCorrente")
                        .HasForeignKey("Sigesp.Domain.Models.ContaCorrente", "ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sigesp.Domain.Models.Empresa", "Empresa")
                        .WithMany("ContasCorrentes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ContaUsuario", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("ContaUsuario")
                        .HasForeignKey("Sigesp.Domain.Models.ContaUsuario", "UserId");
                });

            modelBuilder.Entity("Sigesp.Domain.Models.DetentoSaidaTemporaria", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Detento", "Detento")
                        .WithMany("SaidasTemporaria")
                        .HasForeignKey("DetentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Disciplina", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.EdiLog", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Edi", "Edi")
                        .WithMany("EdiLogs")
                        .HasForeignKey("EdiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.EmpresaConvenio", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Empresa", "Empresa")
                        .WithMany("EmpresaConvenios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Lancamento", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ContaCorrente", "ContaCorrente")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.ContabilEvento", "ContabilEvento")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContabilEventoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sigesp.Domain.Models.ListaAmarela", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.Detento", "Detento")
                        .WithOne("ListaAmarela")
                        .HasForeignKey("Sigesp.Domain.Models.ListaAmarela", "DetentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Livro", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.LivroAutor", "LivroAutor")
                        .WithMany("Livros")
                        .HasForeignKey("LivroAutorId")
                        .IsRequired();

                    b.HasOne("Sigesp.Domain.Models.LivroGenero", "LivroGenero")
                        .WithMany("Livros")
                        .HasForeignKey("LivroGeneroId")
                        .IsRequired();
                });

            modelBuilder.Entity("Sigesp.Domain.Models.Professor", b =>
                {
                    b.HasOne("Sigesp.Domain.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Professor")
                        .HasForeignKey("Sigesp.Domain.Models.Professor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
